import React from 'react';
import { X, Printer, Download, CheckCircle2, Cpu, ShieldCheck } from 'lucide-react';

export default function ReportModal({ isOpen, onClose, msmeData, predictions, shapData, matchedSchemes }) {
  if (!isOpen) return null;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div style={{
      position: 'fixed',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      background: 'rgba(0, 0, 0, 0.75)',
      backdropFilter: 'blur(8px)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 1000,
      padding: '2rem'
    }}>
      <div className="glass-panel" style={{
        width: '100%',
        maxWidth: '850px',
        maxHeight: '90vh',
        overflowY: 'auto',
        background: 'var(--bg-secondary)',
        padding: '2.5rem',
        position: 'relative'
      }}>
        {/* Header bar */}
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: '1px solid var(--border-color)', paddingBottom: '1.25rem', marginBottom: '1.5rem' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
            <Cpu size={28} color="var(--accent-primary)" />
            <div>
              <h2 style={{ fontSize: '1.3rem', fontWeight: 800, color: 'var(--text-primary)' }}>MSME Growth & Advisory Executive Audit</h2>
              <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>Generated by AI-Powered Dual-Layer MSME Platform</p>
            </div>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
            <button onClick={handlePrint} className="btn btn-primary" style={{ padding: '0.5rem 1rem' }}>
              <Printer size={16} /> Print / Save PDF
            </button>
            <button onClick={onClose} className="btn btn-secondary" style={{ padding: '0.5rem' }}>
              <X size={18} />
            </button>
          </div>
        </div>

        {/* Audit Report Content */}
        <div id="printable-report">
          {/* Company Overview */}
          <div style={{ background: 'var(--bg-primary)', padding: '1.25rem', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-color)', marginBottom: '1.5rem', display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '1rem' }}>
            <div>
              <div style={{ fontSize: '0.72rem', color: 'var(--text-muted)' }}>Enterprise Sector</div>
              <div style={{ fontSize: '1rem', fontWeight: 700, color: 'var(--text-primary)' }}>{msmeData.sector}</div>
            </div>
            <div>
              <div style={{ fontSize: '0.72rem', color: 'var(--text-muted)' }}>Annual Revenue</div>
              <div style={{ fontSize: '1rem', fontWeight: 700, color: 'var(--text-primary)' }}>₹{(msmeData.annualRevenue / 100000).toFixed(1)} Lakhs</div>
            </div>
            <div>
              <div style={{ fontSize: '0.72rem', color: 'var(--text-muted)' }}>Workforce Scale</div>
              <div style={{ fontSize: '1rem', fontWeight: 700, color: 'var(--text-primary)' }}>{msmeData.employees} Permanent Staff</div>
            </div>
          </div>

          {/* AI Growth Diagnostic */}
          <div style={{ marginBottom: '1.5rem' }}>
            <h3 style={{ fontSize: '1rem', fontWeight: 700, color: 'var(--text-primary)', marginBottom: '0.75rem' }}>1. Predictive AI Growth Assessment</h3>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '1rem' }}>
              <div style={{ background: 'var(--bg-primary)', padding: '1rem', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-color)' }}>
                <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Growth Score</div>
                <div style={{ fontSize: '1.5rem', fontWeight: 800, color: 'var(--emerald-main)' }}>{predictions.growthScore} / 100</div>
                <div style={{ fontSize: '0.75rem', color: 'var(--text-secondary)' }}>Tier: {predictions.tier}</div>
              </div>
              <div style={{ background: 'var(--bg-primary)', padding: '1rem', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-color)' }}>
                <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>1-Yr Revenue Projection</div>
                <div style={{ fontSize: '1.5rem', fontWeight: 800, color: 'var(--accent-primary)' }}>+{predictions.predictedRevenueGrowth}%</div>
                <div style={{ fontSize: '0.75rem', color: 'var(--text-secondary)' }}>₹{(predictions.projectedRevenueAmount / 100000).toFixed(1)} Lakhs</div>
              </div>
              <div style={{ background: 'var(--bg-primary)', padding: '1rem', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-color)' }}>
                <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Job Creation Potential</div>
                <div style={{ fontSize: '1.5rem', fontWeight: 800, color: 'var(--cyan-main)' }}>+{predictions.predictedJobs} Jobs</div>
                <div style={{ fontSize: '0.75rem', color: 'var(--text-secondary)' }}>Risk: {predictions.riskLevel}</div>
              </div>
            </div>
          </div>

          {/* Top Matched Scheme Recommendations */}
          <div style={{ marginBottom: '1.5rem' }}>
            <h3 style={{ fontSize: '1rem', fontWeight: 700, color: 'var(--text-primary)', marginBottom: '0.75rem' }}>2. Top Recommended Government Schemes</h3>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
              {matchedSchemes.slice(0, 3).map((scheme, idx) => (
                <div key={idx} style={{ background: 'var(--bg-primary)', padding: '1rem', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-color)', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                  <div>
                    <div style={{ fontSize: '0.9rem', fontWeight: 700, color: 'var(--text-primary)', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                      <CheckCircle2 size={16} color="var(--emerald-main)" />
                      {scheme.name}
                    </div>
                    <div style={{ fontSize: '0.78rem', color: 'var(--text-secondary)', marginTop: '0.2rem' }}>
                      {scheme.ministry} • Max Subsidy: ₹{(scheme.maxSubsidy / 100000).toFixed(1)} Lakhs ({scheme.subsidyPercentage}%)
                    </div>
                  </div>
                  <div style={{ textAlign: 'right' }}>
                    <span className="badge badge-emerald">Semantic Match {scheme.semanticScore}%</span>
                    <div style={{ fontSize: '0.8rem', fontWeight: 700, color: 'var(--emerald-main)', marginTop: '0.25rem' }}>
                      Rec. Subsidy: ₹{(scheme.recommendedSubsidyAmount / 100000).toFixed(1)}L
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* SHAP Explanation Summary */}
          <div>
            <h3 style={{ fontSize: '1rem', fontWeight: 700, color: 'var(--text-primary)', marginBottom: '0.75rem' }}>3. Key Value Driver Analysis</h3>
            <p style={{ fontSize: '0.82rem', color: 'var(--text-secondary)', marginBottom: '0.75rem' }}>
              SHAP feature decomposition shows that historical revenue momentum and GST compliance score contribute positively, while debt ratio places a slight drag on credit scoring.
            </p>
          </div>

        </div>

      </div>
    </div>
  );
}
